name: Main Workflow

on:
  pull_request:
    types: [opened, edited]

jobs:
  add_test_cases:
    runs-on: macOS-latest
    name: A job to add Test Cases issues linked to the PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Add TC Issues from PR
        uses: ./myactions
        id: add_tc_issues
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}